server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    adress: 0.0.0.0
  port: 80
  servlet:
    context-path: /star
spring:
  thymeleaf:
    cache:  false
  profiles: # prod dev data
    active: dev
  jmx:
    default-domain: coreBabyangel
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
  main:
    allow-bean-definition-overriding: true